import React from 'react';
import { useNavigate } from 'react-router-dom';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="container py-5">
      
      <div className="p-4 p-md-5">
        {/* Header Section */}
        <div className="text-center mb-5">
          <h1 className="fw-bold gradient-text mb-2">Terms of Service</h1>
          <h5 className="text-muted">Property Investment Analyzer</h5>
          <p className="text-secondary small mb-0">Owned and Operated by Agenthum AI Solutions Pvt. Ltd.</p>
          <p className="text-muted fw-bold small">Last updated: 13 January 2026</p>
        </div>

        {/* Content Section */}
        <div className="content-section text-secondary" style={{ lineHeight: '1.7' }}>
          
          <h4 className="fw-bold mt-4 mb-3">1. Introduction & Acceptance of Terms</h4>
          <p>
            These Terms of Service (“Terms”) govern your access to and use of the <strong>Property Investment Analyzer</strong> (the “App”), available via web or mobile platforms.
          </p>
          <p>
            The App is a proprietary product owned and operated by <strong>Agenthum AI Solutions Pvt. Ltd.</strong> (“Company”, “we”, “us”, or “our”).
          </p>
          <p>By accessing or using the App, you agree to be bound by these Terms. If you do not agree to these Terms, you must discontinue use of the App.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">2. Purpose of the App</h4>
          <p>The Property Investment Analyzer is a calculation and analysis tool designed to help users:</p>
          <ul>
            <li>Analyze property investment scenarios</li>
            <li>Model financial outcomes</li>
            <li>Compare different assumptions and projections</li>
          </ul>
          <p>The App is provided solely for informational and analytical purposes.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">3. No Financial, Investment, Legal, or Tax Advice</h4>
          <p>The App does not provide financial, investment, legal, tax, or professional advice. All results, projections, and insights generated by the App:</p>
          <ul>
            <li>Are based entirely on user-provided data and assumptions</li>
            <li>Use simplified financial formulas and models</li>
            <li>May differ significantly from real-world outcomes</li>
          </ul>
          <p>
            Users should consult qualified professionals (banks, financial advisors, legal or tax experts) before making any financial or investment decisions.
          </p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">4. User Responsibilities</h4>
          <p>You are solely responsible for:</p>
          <ul>
            <li>The accuracy and completeness of all data entered</li>
            <li>The assumptions selected (interest rates, tenure, appreciation, rent, exit price, etc.)</li>
            <li>How you interpret and use the App’s outputs</li>
          </ul>
          <p>The Company does not verify, validate, or audit user inputs.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">5. Estimates, Assumptions & Limitations</h4>
          <p>The App provides estimates and projections only. Actual outcomes may vary due to factors including, but not limited to:</p>
          <ul>
            <li>Bank policies and loan terms</li>
            <li>Interest rate changes</li>
            <li>Construction timelines and possession delays</li>
            <li>Market conditions and property prices</li>
            <li>Taxes, fees, and regulatory changes</li>
          </ul>
          <p>The Company makes no guarantee regarding accuracy, completeness, or future performance of any calculation or result.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">6. No Guarantee of Results</h4>
          <p>The App does not guarantee:</p>
          <ul>
            <li>Investment returns or profits</li>
            <li>Property appreciation or rental income</li>
            <li>Loan approval or loan terms</li>
            <li>Financial success or loss avoidance</li>
          </ul>
          <p>All figures shown are illustrative and non-binding.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">7. Intellectual Property & License</h4>
          <p>
            The App, including its software, calculations, logic, formulas, design, content, and branding, is the exclusive intellectual property of Agenthum AI Solutions Pvt. Ltd.
          </p>
          <p>
            Users are granted a limited, non-exclusive, non-transferable, revocable license to access and use the App for personal or internal analytical purposes only.
          </p>
          <p>
            Users may not copy, modify, distribute, reverse engineer, or commercially exploit any part of the App without prior written consent.
          </p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">8. Third-Party Dependencies</h4>
          <p>The App’s outputs may depend on third-party entities or external factors, including:</p>
          <ul>
            <li>Banks and financial institutions</li>
            <li>Developers and builders</li>
            <li>Government authorities and regulations</li>
            <li>Market and economic conditions</li>
          </ul>
          <p>The Company is not responsible for actions, decisions, or changes made by third parties.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">9. Limitation of Liability</h4>
          <p>
            To the fullest extent permitted by applicable law, Agenthum AI Solutions Pvt. Ltd. shall not be liable for any direct, indirect, incidental, consequential, or financial loss arising from:
          </p>
          <ul>
            <li>Use of or reliance on the App</li>
            <li>Decisions made based on App outputs</li>
            <li>Inaccurate or incomplete user inputs</li>
          </ul>
          <p>Use of the App is entirely at your own discretion and risk.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">10. Data Usage</h4>
          <p>
            User-entered data may be processed temporarily to generate calculations and display results. Unless explicitly stated otherwise, the Company does not guarantee long-term storage of user data.
          </p>
          <p>Please refer to the Privacy Policy for details on data handling.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">11. Modifications to the App or Terms</h4>
          <p>
            We may update, modify, suspend, or discontinue any part of the App or these Terms at any time without prior notice. Continued use of the App after changes constitutes acceptance of the updated Terms.
          </p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">12. Termination of Access</h4>
          <p>
            We reserve the right to suspend or terminate access to the App at our discretion, including for misuse, abuse, or violation of these Terms.
          </p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">13. Governing Law & Jurisdiction</h4>
          <p>These Terms shall be governed by and interpreted in accordance with the laws of India. Courts located in India shall have exclusive jurisdiction over any disputes arising under these Terms.</p>

          <hr className="my-4 opacity-25" />

          <h4 className="fw-bold mt-4 mb-3">14. Contact Information</h4>
          <p>For questions, support, or concerns regarding the App or these Terms, contact:</p>
          
          <div className="glass-card p-3">
            <p className="fw-bold mb-1">Agenthum AI Solutions Pvt. Ltd.</p>
            <p className="mb-1"><i className="bi bi-envelope me-2"></i>Email: support@agenthumsolutions.com</p>
            <p className="mb-0"><i className="bi bi-telephone me-2"></i>Phone: +91 955 582 1832</p>
          </div>

        </div>

        {/* Footer Note */}
        <div className="mt-5 text-center text-muted small border-top pt-3">
          <p className="mb-0">© 2026 Agenthum AI Solutions. All rights reserved.</p>
          <p>Property Investment Analyzer is a product of Agenthum AI Solutions Pvt. Ltd.</p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;